name = "bengawalk-com-notion-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-08"
workers_dev = true

routes = [
	{ pattern = "bengawalk.com", custom_domain = true },
	{ pattern = "www.bengawalk.com", custom_domain = true }
]
